{
  "id": "flyLine",
  "name": "3D中国地图飞线层",
  "version": "V1.0.0",
  "type": "isMapComponents",
  "properties": [{
    "name": "尾迹颜色",
    "editable": "singel",
    "type": "color",
    "value": "#e4df26",
    "properties": []
  }, {
    "name": "尾迹宽度",
    "editable": "singel",
    "type": "range",
    "value": 2,
    "minValue": 0,
    "maxValue": 10,
    "step": 0.1,
    "properties": []
  }, {
    "name": "尾迹长度",
    "editable": "singel",
    "type": "range",
    "value": 0.5,
    "minValue": 0,
    "maxValue": 1,
    "step": 0.01,
    "properties": []
  }, {
    "name": "速度",
    "editable": "singel",
    "type": "range",
    "value": 3,
    "minValue": 0,
    "maxValue": 30,
    "step": 0.1,
    "properties": []
  }, {
    "name": "尾迹透明度",
    "editable": "singel",
    "type": "range",
    "value": 0.8,
    "minValue": 0,
    "maxValue": 1,
    "step": 0.01,
    "properties": []
  }, {
    "name": "线条颜色",
    "editable": "singel",
    "type": "color",
    "value": "transparent",
    "properties": []
  }, {
    "name": "线条透明度",
    "editable": "singel",
    "type": "number",
    "value": 0,
    "minValue": 0,
    "maxValue": 1,
    "step": 0.01,
    "properties": []
  }, {
    "name": "线条粗细",
    "editable": "singel",
    "type": "number",
    "value": 0,
    "minValue": 0,
    "maxValue": 10,
    "step": 0.1,
    "properties": []
  }]
}
