{
  "id": "flyLine",
  "name": "飞线层",
  "version": "V1.0.0",
  "type": "isMapComponents",
  "properties": [{
    "name": "飞出频率",
    "editable": "singel",
    "type": "number",
    "value": 4,
    "minValue": 1,
    "maxValue": 10,
    "step": 1,
    "properties": []
  }, {
    "name": "路径点数",
    "editable": "singel",
    "type": "range",
    "value": 100,
    "minValue": 100,
    "maxValue": 400,
    "step": 1,
    "properties": []
  }, {
    "name": "尾迹长度",
    "editable": "singel",
    "type": "range",
    "value": 0.6,
    "minValue": 0,
    "maxValue": 1,
    "step": 0.01,
    "properties": []
  }, {
    "name": "高度比例",
    "editable": "singel",
    "type": "range",
    "value": 0.2,
    "minValue": 0,
    "maxValue": 1,
    "step": 0.01,
    "properties": []
  }, {
    "name": "起点形状",
    "editable": "singel",
    "type": "select",
    "value": "none",
    "selectData": ["none", "circle", "rect", "roundRect", "triangle", "diamond", "pin", "arrow"],
    "properties": []
  }, {
    "name": "终点形状",
    "editable": "singel",
    "type": "select",
    "value": "none",
    "selectData": ["none", "circle", "rect", "roundRect", "triangle", "diamond", "pin", "arrow"],
    "properties": []
  }, {
    "name": "飞线样式",
    "hasChild": true,
    "editable": "0",
    "properties": [{
      "name": "起点颜色",
      "type": "color",
      "value": "#64E3F9"
    }, {
      "name": "终点颜色",
      "type": "color",
      "value": "#64E3F9"
    }, {
      "name": "耀斑颜色",
      "type": "color",
      "value": "#64E3F9"
    }, {
      "name": "飞线粗细",
      "type": "range",
      "value": 0.5,
      "minValue": 0.01,
      "maxValue": 10,
      "step": 0.04
    }, {
      "name": "飞线透明度",
      "type": "range",
      "value": 0,
      "minValue": 0,
      "maxValue": 1,
      "step": 0.01
    }, {
      "name": "耀斑大小",
      "type": "range",
      "value": 8,
      "minValue": 0.01,
      "maxValue": 20,
      "step": 0.12
    }, {
      "name": "耀斑形状",
      "type": "select",
      "value": "pin",
      "selectData": ["circle", "rect", "roundRect", "triangle", "diamond", "pin", "arrow"]
    }]
  }]
}
