{
  "id": "thermodynamic",
  "name": "区域热力层",
  "version": "V1.0.0",
  "type": "isMapComponents",
  "properties": [{
    "name": "标注",
    "editable": "1",
    "properties": [{
      "name": "标注字段",
      "hasChild": false,
      "editable": "0",
      "type": "none",
      "value": "name",
      "selectData": ["name", "value", "name and value"]
    }, {
      "name": "颜色",
      "hasChild": false,
      "editable": "0",
      "type": "color",
      "value": "#FFFFFF"
    }, {
      "name": "阴影色",
      "hasChild": false,
      "editable": "0",
      "type": "color",
      "value": "#000000"
    }, {
      "name": "字体",
      "hasChild": false,
      "editable": "0",
      "iconName": "fa-question-circle-o",
      "type": "select",
      "value": "微软雅黑",
      "selectData": ["微软雅黑", "宋体", "黑体", "隶书", "幼圆", "tahoma", "arial", "sans-serif"],
      "iconHover": "请选择您系统有的字体,如果您系统无此字体,标题将会显示默认字体"
    }, {
      "name": "字号",
      "hasChild": false,
      "editable": "0",
      "type": "number",
      "minValue": 0,
      "maxValue": 100,
      "value": 12,
      "step": 0.5
    }]
  }, {
    "name": "填充颜色",
    "editable": "0",
    "properties": [{
      "name": "最小值数值",
      "hasChild": false,
      "editable": "0",
      "type": "input",
      "value": 0
    }, {
      "name": "最小值填充色",
      "hasChild": false,
      "editable": "0",
      "type": "color",
      "value": "#05607D"
    }, {
      "name": "最大值数值",
      "hasChild": false,
      "editable": "0",
      "type": "input",
      "value": 1000
    }, {
      "name": "最大值填充色",
      "hasChild": false,
      "editable": "0",
      "type": "color",
      "value": "#05BDBD"
    }, {
      "name": "无数据",
      "hasChild": false,
      "editable": "0",
      "type": "color",
      "value": "#4D4D4D"
    }]
  }, {
    "name": "边线选项",
    "editable": "0",
    "properties": [{
      "name": "颜色",
      "hasChild": false,
      "editable": "0",
      "type": "color",
      "value": "#FFFFFF"
    }, {
      "name": "粗细",
      "hasChild": false,
      "editable": "0",
      "type": "range",
      "value": 1,
      "minValue": 0,
      "maxValue": 10,
      "step": 0.1
    }, {
      "name": "虚线",
      "hasChild": false,
      "editable": "0",
      "type": "select",
      "value": "solid",
      "selectData": ["solid", "dashed", "dotted"]
    }]
  }, {
    "name": "交互配置",
    "editable": "0",
    "properties": [{
      "name": "悬停文字颜色",
      "hasChild": false,
      "editable": "2",
      "type": "color",
      "value": "#FFFFFF"
    }, {
      "name": "悬停区域颜色",
      "hasChild": false,
      "editable": "2",
      "type": "color",
      "value": "#FEE619"
    }, {
      "name": "悬停数据格式",
      "hasChild": false,
      "editable": "0",
      "type": "select",
      "value": "name",
      "selectData": ["name", "value", "name and value"]
    }]
  }, {
    "name": "visualMap配置",
    "editable": "1",
    "properties": [{
      "name": "距左侧百分比",
      "hasChild": false,
      "editable": "0",
      "type": "range",
      "value": 0,
      "minValue": 0,
      "maxValue": 1000,
      "step": 1
    }, {
      "name": "距底部百分比",
      "hasChild": false,
      "editable": "0",
      "type": "range",
      "value": 0,
      "minValue": 0,
      "maxValue": 1000,
      "step": 1
    }]
  }]
}
