{
	"name": "基础仪表盘",
	"id": "dashbord",
	"type": "isDashboard",
	"version": "V1.0.0",
	"properties": [{
		"hasEditProperty": false,
		"editable": "0",
		"name": "基础属性",
		"properties": [{
			"fieldData": [{
				"minValue": 0,
				"name": "宽度",
				"value": 356
			}, {
				"minValue": 0,
				"name": "高度",
				"value": 246
			}],
			"editable": "0",
			"hasChild": false,
			"name": "图表尺寸",
			"type": "number"
		}, {
			"fieldData": [{
				"name": "横坐标",
				"value": 1544
			}, {
				"name": "纵坐标",
				"value": 748
			}],
			"editable": "0",
			"hasChild": false,
			"name": "图表位置",
			"type": "number"
		}, {
			"fieldData": [{
				"minValue": 0,
				"name": "旋转角度",
				"step": 1,
				"value": 0
			}, {
				"minValue": 0,
				"maxValue": 1,
				"name": "透明度",
				"step": 0.1,
				"value": 1
			}],
			"editable": "0",
			"hasChild": false,
			"name": "其他",
			"type": "number"
		}]
	}, {
		"hasEditProperty": false,
		"selectHover": "请选择您系统有的字体,如果您系统无此字体,标题将会显示默认字体",
		"selectData": ["sans-serif", "微软雅黑", "黑体", "digital"],
		"iconName": "fa-question-circle-o",
		"editable": "singel",
		"name": "字体",
		"type": "select",
		"value": "sans-serif",
		"properties": []
	}, {
		"hasEditProperty": false,
		"editable": "0",
		"name": "表盘",
		"properties": [{
			"fieldData": [{
				"minValue": 10,
				"maxValue": 100,
				"name": "字号",
				"step": 0.5,
				"type": "number",
				"value": 25
			}, {
				"name": "颜色",
				"type": "color",
				"value": "#20d6df"
			}, {
				"selectData": ["normal", "bold", "bolder", "lighter", "100", "200", "300", "400", "500", "600", "700", "800", "900"],
				"name": "字体粗细",
				"type": "select",
				"value": "bold"
			}, {
				"name": "单位",
				"type": "input",
				"value": "%"
			}],
			"editable": "1",
			"hasChild": true,
			"name": "详情",
			"type": "hasChild"
		}, {
			"fieldData": [{
				"minValue": 0,
				"maxValue": 1,
				"name": "半径",
				"step": 0.01,
				"type": "range",
				"value": 0.75
			}, {
				"minValue": -360,
				"maxValue": 360,
				"name": "起始角度",
				"step": 1,
				"type": "range",
				"value": 215
			}, {
				"minValue": -360,
				"maxValue": 360,
				"name": "结束角度",
				"step": 1,
				"type": "range",
				"value": -35
			}, {
				"name": "最小值",
				"step": 1,
				"type": "number",
				"value": 0
			}, {
				"name": "最大值",
				"step": 1,
				"type": "number",
				"value": 100
			}, {
				"selectData": ["顺时针", "逆时针"],
				"name": "方向",
				"type": "select",
				"value": "顺时针"
			}, {
				"minValue": 1,
				"maxValue": 100,
				"name": "分隔段数",
				"step": 1,
				"type": "number",
				"value": 10
			}],
			"editable": "0",
			"hasChild": true,
			"name": "基本属性",
			"type": "hasChild"
		}, {
			"fieldData": [{
				"selectData": ["颜色填充", "渐变填充"],
				"fieldData": [{
					"type": "color",
					"value": "#008ebd"
				}, {
					"fieldData": [{
						"type": "color",
						"value": "#00caca"
					}, {
						"type": "color",
						"value": "#0581af"
					}, {
						"minValue": 0,
						"maxValue": 360,
						"step": 2,
						"type": "range",
						"value": 90
					}],
					"type": "multiColor"
				}],
				"name": "颜色",
				"type": "multiColor",
				"value": "渐变填充"
			}, {
				"name": "宽度",
				"step": 1,
				"type": "number",
				"value": 30
			}],
			"editable": "1",
			"hasChild": true,
			"name": "轴线",
			"type": "hasChild"
		}, {
			"fieldData": [{
				"name": "长度",
				"step": 1,
				"type": "number",
				"value": 30
			}, {
				"name": "宽度",
				"step": 1,
				"type": "number",
				"value": 2
			}, {
				"name": "颜色",
				"type": "color",
				"value": "#0E2A42 "
			}],
			"editable": "1",
			"hasChild": true,
			"name": "分隔线",
			"type": "hasChild"
		}, {
			"fieldData": [{
				"name": "数量",
				"step": 1,
				"type": "number",
				"value": 5
			}, {
				"name": "长度",
				"step": 1,
				"type": "number",
				"value": 8
			}, {
				"name": "颜色",
				"type": "color",
				"value": "#eee "
			}],
			"editable": "2",
			"hasChild": true,
			"name": "刻度",
			"type": "hasChild"
		}, {
			"fieldData": [{
				"fieldData": [{
					"minValue": 10,
					"maxValue": 100,
					"name": "字号",
					"step": 0.5,
					"type": "number",
					"value": 15
				}, {
					"name": "颜色",
					"type": "color",
					"value": "#ffffff"
				}, {
					"selectData": ["normal", "bold", "bolder", "lighter", "100", "200", "300", "400", "500", "600", "700", "800", "900"],
					"name": "字体粗细",
					"type": "select",
					"value": "normal"
				}],
				"editable": "0",
				"hasChild": true,
				"name": "文本",
				"type": "hasChild"
			}, {
				"name": "距离",
				"step": 1,
				"type": "number",
				"value": -55
			}],
			"editable": "2",
			"hasChild": true,
			"name": "刻度标签",
			"type": "hasChild"
		}]
	}, {
		"hasEditProperty": true,
		"editable": "1",
		"name": "指针",
		"properties": [{
			"minValue": 0,
			"maxValue": 1,
			"name": "长度",
			"step": 0.01,
			"type": "range",
			"value": 0.7
		}, {
			"name": "宽度",
			"step": 1,
			"type": "number",
			"value": 5
		}, {
			"name": "颜色",
			"type": "color",
			"value": "#ffffff"
		}]
	}, {
		"hasEditProperty": true,
		"editable": "1",
		"name": "标题",
		"properties": [{
			"name": "颜色",
			"type": "color",
			"value": "#ffffff"
		}, {
			"minValue": 10,
			"maxValue": 100,
			"name": "字号",
			"step": 0.5,
			"type": "number",
			"value": 16
		}, {
			"name": "字体",
			"type": "select",
			"value": "sans-serif",
			"selectData": ["sans-serif", "微软雅黑", "黑体","digital"]
		}, {
			"name": "字体粗细",
			"type": "select",
			"value": "normal",
			"selectData": ["normal", "bold", "bolder", "lighter", "100", "200", "300", "400", "500", "600", "700", "800", "900"]
		}, {
			"minValue": -100,
			"maxValue": 100,
			"name": "水平偏移",
			"step": 1,
			"type": "range",
			"value": 0
		}, {
			"minValue": -100,
			"maxValue": 100,
			"name": "垂直偏移",
			"step": 1,
			"type": "range",
			"value": 80
		}]
	}, {
		"hasEditProperty": true,
		"editable": "1",
		"name": "动画",
		"properties": [{
			"name": "初始动画时长",
			"step": 1,
			"type": "number",
			"value": 1000
		}, {
			"selectData": ["linear", "quadraticIn", "quadraticOut", "quadraticInOut", "cubicIn", "cubicOut", "cubicInOut", "quarticIn", "quarticOut", "quarticInOut", "quinticIn", "quinticOut", "quinticInOut", "sinusoidalIn", "sinusoidalOut", "sinusoidalInOut", "exponentialIn", "exponentialOut", "exponentialInOut", "circularIn", "circularOut", "circularInOut", "elasticIn", "elasticOut", "elasticInOut", "backIn", "backOut", "backInOut", "bounceIn", "bounceOut", "bounceInOut"],
			"name": "缓动效果",
			"type": "select",
			"value": "linear"
		}, {
			"name": "更新动画时长",
			"step": 1,
			"type": "number",
			"value": 300
		}, {
			"fieldData": [{
				"name": "从之前位置开始",
				"value": true
			}],
			"editable": "0",
			"hasChild": false,
			"name": "从之前位置开始",
			"type": "radio"
		}]
	}]
}
