{
  "id": "moveBarList",
  "name": "轮播柱状列表",
  "version": "V1.0.0",
  "type": "isList",
  "properties": [{
      "name": "基础属性",
      "hasEditProperty": false,
      "editable": "0",
      "properties": [{
        "name": "图表尺寸",
        "type": "number",
        "hasChild": false,
        "editable": "0",
        "fieldData": [{
          "name": "宽度",
          "value": 400,
          "minValue": 0
        }, {
          "name": "高度",
          "value": 200,
          "minValue": 0
        }]
      }, {
        "name": "图表位置",
        "hasChild": false,
        "editable": "0",
        "type": "number",
        "fieldData": [{
          "name": "横坐标",
          "value": 810
        }, {
          "name": "纵坐标",
          "value": 440
        }]
      }, {
        "name": "其他",
        "hasChild": false,
        "editable": "0",
        "type": "number",
        "fieldData": [{
          "name": "旋转角度",
          "minValue": 0,
          "value": 0,
          "step": 1
        }, {
          "name": "透明度",
          "value": 1,
          "minValue": 0,
          "maxValue": 1,
          "step": 0.1
        }]
      }]
    },
    {
      "name": "全局",
      "editable": "0",
      "properties": [{
        "name": "表格行数",
        "hasChild": false,
        "editable": "0",
        "type": "number",
        "minValue": 1,
        "maxValue": 50,
        "value": 5,
        "step": 1
      }, {
        "name": "字体",
        "hasChild": false,
        "editable": "0",
        "iconName": "fa-question-circle-o",
        "type": "select",
        "value": "微软雅黑",
        "selectData": ["微软雅黑", "宋体", "黑体", "隶书", "幼圆", "tahoma", "arial", "sans-serif"],
        "iconHover": "请选择您系统有的字体,如果您系统无此字体,标题将会显示默认字体"
      }, {
        "name": "自动轮播",
        "hasChild": false,
        "editable": "0",
        "type": "radio",
        "fieldData": [{
          "name": "自动轮播",
          "value": true
        }]
      }, {
        "name": "轮播时间(秒)",
        "editable": "0",
        "hasChild": false,
        "parentName": "animation",
        "type": "number",
        "minValue": 1,
        "maxValue": 20,
        "value": 1,
        "step": 0.5
      }, {
        "name": "动画间隔(秒)",
        "editable": "0",
        "hasChild": false,
        "type": "number",
        "minValue": 1,
        "maxValue": 20,
        "value": 2,
        "step": 0.5
      }, {
        "name": "内容",
        "hasChild": true,
        "editable": "0",
        "type": "hasChild",
        "fieldData": [{
          "name": "字号",
          "type": "range",
          "value": 12,
          "minValue": 0,
          "maxValue": 200,
          "step": 1
        }, {
          "name": "颜色",
          "type": "color",
          "value": "#ffffff"
        }, {
          "name": "字体粗细",
          "type": "select",
          "value": "normal",
          "selectData": ["normal", "bold", "bolder", "lighter", "100", "200", "300", "400", "500", "600", "700", "800", "900"]
        }, {
          "name": "溢出滚动",
          "type": "radio",
          "fieldData": [{
            "name": "溢出滚动",
            "value": false
          }]
        }, {
          "name": "滚动时间(秒)",
          "type": "number",
          "minValue": 0.5,
          "maxValue": 20,
          "value": 5,
          "step": 0.5
        }, {
          "name": "列宽占比",
          "type": "number",
          "minValue": 0,
          "maxValue": 2000,
          "value": 68,
          "step": 0.5
        }]
      }, {
        "name": "数值",
        "hasChild": true,
        "editable": "1",
        "type": "hasChild",
        "fieldData": [{
          "name": "字号",
          "type": "range",
          "value": 12,
          "minValue": 0,
          "maxValue": 200,
          "step": 1
        }, {
          "name": "颜色",
          "type": "color",
          "value": "#ffffff"
        }, {
          "name": "字体粗细",
          "type": "select",
          "value": "normal",
          "selectData": ["normal", "bold", "bolder", "lighter", "100", "200", "300", "400", "500", "600", "700", "800", "900"]
        }, {
          "name": "列宽占比",
          "type": "number",
          "minValue": 0,
          "maxValue": 2000,
          "value": 20,
          "step": 0.5
        }]
      }]
    },
    {
      "name": "行配置",
      "editable": "0",
      "properties": [{
        "name": "奇行背景色",
        "hasChild": false,
        "editable": "0",
        "type": "color",
        "value": "transparent"
      }, {
        "name": "偶行背景色",
        "hasChild": false,
        "editable": "0",
        "type": "color",
        "value": "transparent"
      }]
    }, {
      "name": "序号列",
      "editable": "1",
      "properties": [{
        "name": "列宽占比",
        "hasChild": false,
        "editable": "0",
        "type": "range",
        "value": 12,
        "minValue": 0,
        "maxValue": 100,
        "step": 1
      }, {
        "name": "文本样式",
        "hasChild": true,
        "editable": "0",
        "type": "hasChild",
        "fieldData": [{
          "name": "字体颜色",
          "type": "color",
          "value": "#ffffff"
        }, {
          "name": "字号",
          "type": "range",
          "value": 12,
          "minValue": 0,
          "maxValue": 50,
          "step": 1
        }, {
          "name": "字体粗细",
          "type": "select",
          "value": "normal",
          "selectData": ["normal", "bold", "bolder", "lighter", "100", "200", "300", "400", "500", "600", "700", "800", "900"]
        }]
      }]
    }, {
      "name": "柱状图",
      "editable": "1",
      "properties": [{
        "name": "颜色",
        "hasChild": false,
        "editable": "0",
        "type": "color",
        "value": "#00BAFF"
      }, {
        "name": "高度",
        "hasChild": false,
        "editable": "0",
        "type": "number",
        "value": 4,
        "minValue": 0,
        "maxValue": 500,
        "step": 0.5
      }]
    }, {
      "name": "流光",
      "editable": "1",
      "properties": [{
        "name": "颜色",
        "hasChild": false,
        "editable": "0",
        "type": "color",
        "value": "#28F8FF"
      }, {
        "name": "长度",
        "hasChild": false,
        "editable": "0",
        "type": "number",
        "value": 35,
        "minValue": 0,
        "maxValue": 1000,
        "step": 0.5
      }, {
        "name": "高度",
        "hasChild": false,
        "editable": "0",
        "type": "number",
        "value": 2,
        "minValue": 0,
        "maxValue": 500,
        "step": 0.5
      }, {
        "name": "动画时间(秒)",
        "editable": "0",
        "hasChild": false,
        "type": "number",
        "minValue": 1,
        "maxValue": 20,
        "value": 1,
        "step": 0.5
      }]
    }, {
      "name": "分割线",
      "editable": "1",
      "properties": [{
        "name": "颜色",
        "hasChild": false,
        "editable": "0",
        "type": "color",
        "value": "#0a5b79"
      }]
    }
  ]
}
